### ISSUE TITLE
New block header field

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrusrb#4]
In tapyrus, BlockHeader has fields:
- features
- has_prev_block
- hash_merkle_root
- hash_im_merkle_root
- time
- xfield_type
- xfield
- proof

hash_im_merkle_root, xfield_type, xfield and proof should be added.

see https://github.com/chaintope/tapyrus-core/blob/master/doc/tapyrus/signedblocks.md

**Comment by azuchi** [comment]
Fixed by https://github.com/chaintope/tapyrusrb/commit/2574b116bd78178c1cafe3e7d57ffc8ac3bcb00a
